"""Shared constants for the Stock Lakehouse platform."""

from __future__ import annotations

# US stocks universe - ~300 liquid large/mid-cap tickers across sectors.
# Chosen for daily liquidity on Yahoo Finance (5-10+ year history available).
# Sources: S&P 500 / NASDAQ-100 / Dow 30 / popular ETFs / major ADRs.
US_SYMBOLS: list[str] = [
    "A",
    "AAL",
    "AAPL",
    "ABBV",
    "ABNB",
    "ABT",
    "ACAD",
    "ACHC",
    "ACI",
    "ACLS",
    "ADBE",
    "ADI",
    "ADM",
    "ADP",
    "AEE",
    "AEHR",
    "AEM",
    "AEO",
    "AEP",
    "AES",
    "AFL",
    "AG",
    "AGG",
    "AJG",
    "AKRO",
    "ALB",
    "ALK",
    "ALL",
    "ALLE",
    "ALLY",
    "ALTM",
    "ALXN",
    "AMAT",
    "AMD",
    "AMGN",
    "AMP",
    "AMT",
    "AMZN",
    "AN",
    "ANET",
    "ANF",
    "AON",
    "AOS",
    "APA",
    "APD",
    "AR",
    "ARCB",
    "ARE",
    "ARKF",
    "ARKK",
    "ARKW",
    "ARM",
    "ARVN",
    "ASML",
    "ATO",
    "ATSG",
    "ATVI",
    "AU",
    "AVA",
    "AVB",
    "AVGO",
    "AVTE",
    "AWK",
    "AWR",
    "AXP",
    "AYI",
    "AZO",
    "BA",
    "BAC",
    "BAX",
    "BBIO",
    "BBWI",
    "BBY",
    "BDN",
    "BDX",
    "BEAM",
    "BG",
    "BIIB",
    "BIL",
    "BIO",
    "BIP",
    "BITO",
    "BITQ",
    "BITX",
    "BJRI",
    "BK",
    "BKH",
    "BKNG",
    "BLDR",
    "BLK",
    "BLMN",
    "BLUE",
    "BMRN",
    "BND",
    "BNDX",
    "BNTX",
    "BP",
    "BRO",
    "BRX",
    "BSX",
    "BTF",
    "BURL",
    "BXP",
    "C",
    "CAG",
    "CAKE",
    "CAR",
    "CAT",
    "CBOE",
    "CBRL",
    "CC",
    "CCEP",
    "CCI",
    "CCJ",
    "CCRN",
    "CDE",
    "CDNS",
    "CELH",
    "CF",
    "CFG",
    "CHD",
    "CHE",
    "CHK",
    "CHRW",
    "CHTR",
    "CINF",
    "CL",
    "CLH",
    "CMA",
    "CMCSA",
    "CME",
    "CMG",
    "CMI",
    "CMS",
    "CNP",
    "CNX",
    "COF",
    "COP",
    "COR",
    "COST",
    "CPB",
    "CPRI",
    "CPRX",
    "CPT",
    "CRM",
    "CRSP",
    "CRWD",
    "CSCO",
    "CSX",
    "CTO",
    "CTRA",
    "CUZ",
    "CVX",
    "CWT",
    "D",
    "DAL",
    "DASH",
    "DAWN",
    "DD",
    "DDOG",
    "DE",
    "DEI",
    "DELL",
    "DENN",
    "DG",
    "DGX",
    "DHR",
    "DIA",
    "DIN",
    "DIS",
    "DLR",
    "DLTR",
    "DOC",
    "DOCS",
    "DOCU",
    "DOV",
    "DOW",
    "DPZ",
    "DRI",
    "DTE",
    "DUK",
    "DVN",
    "EA",
    "EAT",
    "EBAY",
    "ECL",
    "ED",
    "EEM",
    "EFA",
    "EIX",
    "ELAN",
    "EMR",
    "ENB",
    "ENSG",
    "ENTG",
    "EOG",
    "EPD",
    "EQIX",
    "EQNR",
    "EQR",
    "EQT",
    "ERIE",
    "ES",
    "ESS",
    "ESTC",
    "ETHE",
    "ETN",
    "ETR",
    "ETSY",
    "EW",
    "EXC",
    "EXEL",
    "EXP",
    "EXPE",
    "EXPR",
    "EXR",
    "F",
    "FAF",
    "FANG",
    "FAST",
    "FATE",
    "FCX",
    "FDX",
    "FE",
    "FICO",
    "FITB",
    "FLO",
    "FNF",
    "FNKO",
    "FNV",
    "FOLD",
    "FORM",
    "FOX",
    "FOXA",
    "FROG",
    "FRT",
    "FTNT",
    "GBTC",
    "GD",
    "GE",
    "GILD",
    "GIS",
    "GLBE",
    "GLD",
    "GM",
    "GNRC",
    "GOLD",
    "GOOG",
    "GOOGL",
    "GS",
    "GTLB",
    "GTY",
    "HALO",
    "HAS",
    "HBAN",
    "HD",
    "HDV",
    "HEI",
    "HIG",
    "HIW",
    "HL",
    "HOLX",
    "HON",
    "HPE",
    "HPQ",
    "HQY",
    "HR",
    "HRB",
    "HRL",
    "HST",
    "HSY",
    "HWM",
    "HYG",
    "IBM",
    "ICE",
    "ICL",
    "ICLR",
    "IDXX",
    "IEF",
    "ILMN",
    "IMVT",
    "INCY",
    "INTC",
    "INTU",
    "IOVA",
    "IPG",
    "IR",
    "IRON",
    "ISRG",
    "ITW",
    "IWM",
    "JACK",
    "JAZZ",
    "JBHT",
    "JBLU",
    "JNJ",
    "JPM",
    "KDP",
    "KEY",
    "KGC",
    "KHC",
    "KIM",
    "KLAC",
    "KLG",
    "KMI",
    "KMX",
    "KNX",
    "KO",
    "KR",
    "KRC",
    "KRYS",
    "KSS",
    "KYMR",
    "LAC",
    "LCID",
    "LH",
    "LI",
    "LIN",
    "LLY",
    "LMT",
    "LNT",
    "LOW",
    "LQD",
    "LRCX",
    "LTHM",
    "LUV",
    "LYFT",
    "LYV",
    "M",
    "MA",
    "MAA",
    "MAC",
    "MAS",
    "MAT",
    "MBLY",
    "MCD",
    "MCHP",
    "MDT",
    "MEDP",
    "MELI",
    "MET",
    "META",
    "MGEE",
    "MGM",
    "MGNX",
    "MKTX",
    "MLM",
    "MMM",
    "MNDY",
    "MNST",
    "MO",
    "MOS",
    "MPC",
    "MPLX",
    "MPWR",
    "MRK",
    "MRNA",
    "MS",
    "MSFT",
    "MSI",
    "MTB",
    "MTCH",
    "MTD",
    "MTDR",
    "MTUM",
    "MU",
    "MUB",
    "NBIX",
    "NDAQ",
    "NEE",
    "NEM",
    "NEO",
    "NET",
    "NFG",
    "NFLX",
    "NGL",
    "NHI",
    "NI",
    "NIO",
    "NJR",
    "NKE",
    "NNN",
    "NOC",
    "NOW",
    "NRG",
    "NSC",
    "NTLA",
    "NTR",
    "NTRA",
    "NTRS",
    "NVAX",
    "NVDA",
    "NVMI",
    "NWE",
    "NWS",
    "NWSA",
    "O",
    "OC",
    "OCGN",
    "ODFL",
    "OGE",
    "OGS",
    "OHI",
    "OKE",
    "OKTA",
    "OMC",
    "ON",
    "OR",
    "ORCL",
    "ORLY",
    "OUT",
    "OVV",
    "OXY",
    "PAA",
    "PAAS",
    "PANW",
    "PARA",
    "PAYC",
    "PBR",
    "PCAR",
    "PCG",
    "PEAK",
    "PEG",
    "PEP",
    "PFE",
    "PFGC",
    "PG",
    "PGR",
    "PGRE",
    "PH",
    "PINS",
    "PLD",
    "PLL",
    "PLTR",
    "PM",
    "PNC",
    "PNR",
    "PNW",
    "POST",
    "POWL",
    "PPG",
    "PPL",
    "PR",
    "PRGO",
    "PRME",
    "PRU",
    "PSA",
    "PSNL",
    "PSX",
    "PTCT",
    "PTGX",
    "PVH",
    "PYPL",
    "PZZA",
    "QCOM",
    "QQQ",
    "QRVO",
    "QSR",
    "QUAL",
    "RARE",
    "RBLX",
    "REG",
    "REGN",
    "REXR",
    "RF",
    "RGLD",
    "RIGL",
    "RIVN",
    "RJF",
    "RL",
    "ROKU",
    "ROP",
    "ROST",
    "RRC",
    "RSG",
    "RTX",
    "RVMD",
    "S",
    "SAP",
    "SBUX",
    "SCHD",
    "SCHW",
    "SHEL",
    "SHOP",
    "SHW",
    "SHY",
    "SJM",
    "SKT",
    "SLB",
    "SLG",
    "SLV",
    "SNAP",
    "SNDR",
    "SNOW",
    "SNPS",
    "SO",
    "SOXL",
    "SPB",
    "SPG",
    "SPGI",
    "SPOT",
    "SPXU",
    "SPY",
    "SQM",
    "SQQQ",
    "SR",
    "SRE",
    "SSRM",
    "STLA",
    "STM",
    "STT",
    "SWK",
    "SWKS",
    "SWX",
    "SYF",
    "SYK",
    "SYY",
    "T",
    "TARS",
    "TCO",
    "TDG",
    "TDY",
    "TEAM",
    "TFC",
    "TGNA",
    "TGT",
    "TGTX",
    "TIP",
    "TJX",
    "TLT",
    "TMO",
    "TMUS",
    "TPL",
    "TPR",
    "TQQQ",
    "TROX",
    "TRP",
    "TRV",
    "TSLA",
    "TSM",
    "TSN",
    "TTD",
    "TTE",
    "TW",
    "TWLO",
    "TXN",
    "TXRH",
    "TXT",
    "U",
    "UAL",
    "UBER",
    "UCTT",
    "UDR",
    "ULTA",
    "UNFI",
    "UNG",
    "UNH",
    "UNP",
    "UPRO",
    "UPS",
    "URA",
    "URBN",
    "USB",
    "USFD",
    "USMV",
    "USO",
    "UTHR",
    "UUUU",
    "UVV",
    "V",
    "VEA",
    "VEEV",
    "VFC",
    "VICI",
    "VIG",
    "VLO",
    "VMC",
    "VNO",
    "VNOM",
    "VOO",
    "VRSK",
    "VRTX",
    "VTEB",
    "VTI",
    "VTR",
    "VTV",
    "VUG",
    "VWO",
    "VZ",
    "WAT",
    "WBA",
    "WBD",
    "WCN",
    "WDAY",
    "WEC",
    "WELL",
    "WERN",
    "WEST",
    "WFC",
    "WING",
    "WM",
    "WMB",
    "WMT",
    "WOLF",
    "WPM",
    "WRB",
    "WTW",
    "XEL",
    "XOM",
    "XPEV",
    "XPO",
    "XRAY",
    "XYL",
    "YELP",
    "YPF",
    "YUM",
    "ZBH",
    "ZION",
    "ZM",
    "ZS",
    "ZTS",
]


# ── Global universe — 500+ tickers across regions/sectors ──────────────
# Curated for daily Yahoo Finance coverage (5-year history).
# Mix: US large/mid-cap, EU blue-chips, Japan/HK/China ADRs, EM, sectors ETFs.
GLOBAL_SYMBOLS: list[str] = list(US_SYMBOLS) + [
    # ── Europe (Germany) ───────────────────────────────────────────────
    "ADS.DE", "ALV.DE", "BAS.DE", "BAYN.DE", "BMW.DE", "BNR.DE", "CON.DE",
    "DB1.DE", "DBK.DE", "DHL.DE", "DTE.DE", "EOAN.DE", "FRE.DE", "HEIA.DE",
    "HEN3.DE", "IFX.DE", "LIN.DE", "MBG.DE", "MRK.DE", "MTX.DE", "MUV2.DE",
    "P911.DE", "PAH3.DE", "QIA.DE", "RWE.DE", "SAP.DE", "SIE.DE", "VOW3.DE",
    "VNA.DE", "ZAL.DE",

    # ── Europe (France) ────────────────────────────────────────────────
    "AI.PA", "AIR.PA", "BNP.PA", "BN.PA", "CA.PA", "CAP.PA", "CS.PA",
    "DG.PA", "EL.PA", "ENGI.PA", "EN.PA", "GLE.PA", "HO.PA", "MC.PA",
    "ML.PA", "OR.PA", "PUB.PA", "RNO.PA", "SAF.PA", "SAN.PA", "SGO.PA",
    "STLA.PA", "SU.PA", "TTE.PA", "VIE.PA", "VIV.PA",

    # ── Europe (UK / Netherlands / Spain / Italy / Switzerland) ───────
    "SHEL.L", "AZN.L", "HSBA.L", "BP.L", "ULVR.L", "DGE.L", "GSK.L",
    "RIO.L", "BARC.L", "LSEG.L", "LLOY.L", "NG.L", "REL.L", "TSCO.L",
    "VOD.L", "PRTY.L", "ASML.AS", "AD.AS", "INGA.AS", "PHIA.AS", "UNA.AS",
    "SAN.MC", "IBE.MC", "ITX.MC", "TEF.MC", "ENI.MI", "ISP.MI", "ENEL.MI",
    "RACE.MI", "NESN.SW", "NOVN.SW", "ROG.SW", "UBSG.SW", "ABBN.SW",

    # ── Japan (Yahoo uses .T suffix) ───────────────────────────────────
    "7203.T", "6758.T", "9984.T", "8306.T", "6861.T", "7974.T", "9433.T",
    "8035.T", "4063.T", "6501.T", "7267.T", "7751.T", "6902.T", "6367.T",
    "7741.T", "4502.T", "4503.T", "2802.T", "2914.T", "3407.T", "4452.T",
    "9020.T", "9022.T", "6098.T", "4661.T", "6954.T", "6981.T", "6594.T",
    "9432.T", "9434.T", "4689.T", "9613.T", "3659.T", "9983.T", "3382.T",
    "8411.T", "8316.T", "6752.T", "7269.T", "8801.T",

    # ── Hong Kong ──────────────────────────────────────────────────────
    "0700.HK", "9988.HK", "3690.HK", "9618.HK", "1810.HK", "0941.HK",
    "1299.HK", "0005.HK", "0001.HK", "0016.HK", "0027.HK", "0066.HK",
    "0388.HK", "1398.HK", "0939.HK", "3988.HK", "2628.HK", "823.HK",
    "2388.HK", "0023.HK",

    # ── China (ADRs) ───────────────────────────────────────────────────
    "BABA", "JD", "PDD", "BIDU", "NIO", "XPEV", "LI", "TME", "BILI",
    "NTES", "ZTO", "YUMC", "EDU", "TAL", "VIPS", "KC", "FUTU", "TIGR",
    "ACH", "YMM", "NOAH",

    # ── India (ADRs) ───────────────────────────────────────────────────
    "INFY", "WIT", "IBN", "HDB", "RDY", "TTM", "SIFY", "MMYT",

    # ── Brazil / LatAm (ADRs) ──────────────────────────────────────────
    "VALE", "ITUB", "BBD", "PBR", "ABV", "ERJ", "GOL", "BSBR", "SBSA",
    "UGP", "LMT", "STNE",

    # ── Canada ──────────────────────────────────────────────────────────
    "SHOP", "RY.TO", "TD.TO", "ENB.TO", "BNS.TO", "BMO.TO", "CNR.TO",
    "CP.TO", "L.TO", "SU.TO", "BAM.TO", "MFC.TO", "FNV.TO", "ABX.TO",
    "GOLD", "TRI.TO", "WCN.TO", "QSR.TO", "MG.TO",

    # ── Australia ──────────────────────────────────────────────────────
    "BHP.AX", "CBA.AX", "CSL.AX", "NAB.AX", "WBC.AX", "ANZ.AX", "WES.AX",
    "MQG.AX", "FMG.AX", "TLS.AX", "WOW.AX", "COL.AX", "IAG.AX", "JHX.AX",
    "STO.AX", "NCM.AX", "WPL.AX", "RIO.AX", "TWE.AX", "REA.AX",

    # ── South Korea (Yahoo .KS suffix) ──────────────────────────────────
    "005930.KS", "000660.KS", "035420.KS", "051910.KS", "005380.KS",
    "006400.KS", "035720.KS", "028260.KS", "068270.KS", "003550.KS",
    "015760.KS", "033780.KS", "096770.KS", "017670.KS", "066570.KS",
    "003490.KS", "034730.KS", "032830.KS", "009150.KS", "010950.KS",

    # ── Taiwan ──────────────────────────────────────────────────────────
    "2330.TW", "2317.TW", "2454.TW", "2308.TW", "2881.TW", "2882.TW",
    "2885.TW", "2886.TW", "2891.TW", "2883.TW", "1101.TW", "1301.TW",
    "1303.TW", "1326.TW", "1590.TW", "2379.TW", "3008.TW", "3034.TW",
    "3037.TW", "3711.TW",

    # ── Sector / Thematic ETFs (US) ────────────────────────────────────
    "XLK", "XLF", "XLE", "XLV", "XLY", "XLP", "XLI", "XLU", "XLB", "XLRE",
    "XLC", "VGT", "VHT", "VFH", "VDE", "VCR", "VDC", "VIS", "VPU", "VAW",
    "VNQ", "ARKK", "ARKW", "SOXL", "SOXS", "TQQQ", "SQQQ", "UVXY", "VXX",
    "GLD", "SLV", "USO", "UNG", "DBA", "DBC", "BNO", "AGG", "TLT", "SHY",
    "IEF", "LQD", "HYG", "JNK", "MUB", "BIL", "TIP", "SCHD", "VYM", "DGRO",
    "SPYV", "QUAL", "MTUM", "VLUE", "USMV", "VTV", "VUG", "IVW", "IWF",
    "IWD", "IWB", "IWM", "IWO", "IWN", "IWS", "IWP", "IWR", "IWV",
]

# All non-VN, non-crypto, non-index supported symbols = US_SYMBOLS
SUPPORTED_SYMBOLS: list[str] = list(US_SYMBOLS)

# Market Indexes (for benchmarking)
MARKET_INDEXES: list[str] = [
    "^GSPC",   # S&P 500
    "^DJI",    # Dow Jones
    "^IXIC",   # NASDAQ
]

# Crypto (via Yahoo Finance) — kept for completeness
CRYPTO_SYMBOLS: list[str] = [
    "BTC-USD",  # Bitcoin
    "ETH-USD",  # Ethereum
]

# All available symbols — global universe (500+ tickers across regions/sectors).
ALL_SYMBOLS: list[str] = list(GLOBAL_SYMBOLS) + MARKET_INDEXES + CRYPTO_SYMBOLS

# Intervals - only 1d is collected (single-interval lakehouse)
SUPPORTED_INTERVALS: list[str] = ["1d"]

OHLCV_COLUMNS: list[str] = [
    "symbol",
    "timestamp",
    "open",
    "high",
    "low",
    "close",
    "adj_close",
    "volume",
    "source",
    "ingestion_time",
]

BRONZE_PARTITION_COLUMNS: list[str] = ["symbol", "year", "month"]

GOLD_FEATURE_COLUMNS: list[str] = [
    "return",
    "log_return",
    "price_change",
    "volume_change",
    "sma_5",
    "sma_10",
    "sma_20",
    "sma_50",
    "ema_12",
    "ema_26",
    "rsi_14",
    "macd",
    "macd_signal",
    "macd_hist",
    "bb_middle",
    "bb_upper",
    "bb_lower",
    "rolling_std_20",
    "rolling_min_20",
    "rolling_max_20",
    "volume_ma_20",
    "close_lag_1",
    "close_lag_2",
    "return_lag_1",
    "volume_lag_1",
]

GOLD_TARGET_COLUMNS: list[str] = [
    "target_close_next",
    "target_return_next",
    "target_direction_next",
]

LINEAR_REGRESSION_FEATURES: list[str] = [
    "close",
    "volume",
    "return",
    "sma_5",
    "sma_10",
    "sma_20",
    "sma_50",
    "ema_12",
    "ema_26",
    "rsi_14",
    "macd",
    "macd_signal",
    "macd_hist",
    "bb_middle",
    "bb_upper",
    "bb_lower",
    "rolling_std_20",
    "close_lag_1",
    "close_lag_2",
    "return_lag_1",
    "volume_lag_1",
]

LSTM_FEATURE_COLUMNS: list[str] = [
    "close",
    "volume",
    "return",
    "sma_20",
    "ema_12",
    "rsi_14",
    "macd",
    "bb_middle",
    "rolling_std_20",
]

ACADEMIC_DISCLAIMER = (
    "Kết quả phân tích và dự báo chỉ phục vụ nghiên cứu học thuật, "
    "không phải khuyến nghị đầu tư và không cam kết lợi nhuận tương lai."
)

INTERVAL_TO_PANDAS_FREQ: dict[str, str] = {
    "1d": "B",
    "1h": "h",
    "15m": "15min",
    "5m": "5min",
}

INTERVAL_BARS_PER_YEAR: dict[str, int] = {
    "1d": 252,
    "1h": 252 * 6.5,
    "15m": 252 * 26,
    "5m": 252 * 78,
}
